models/Autores.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "autores".
 *
 * @property int $id
 * @property string|null $nombre
 * @property string|null $apellidos
 */
class Autores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'autores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'apellidos'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'apellidos' => 'Apellidos',
        ];
    }
}

models/Libros.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "libros".
 *
 * @property int $id
 * @property string|null $ISBN
 * @property string|null $titulo
 * @property string|null $fecha_publicacion
 */
class Libros extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'libros';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fecha_publicacion'], 'safe'],
            [['ISBN', 'titulo'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ISBN' => 'Isbn',
            'titulo' => 'Titulo',
            'fecha_publicacion' => 'Fecha Publicacion',
        ];
    }
}

models/Mensajes.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "mensajes".
 *
 * @property int $id
 * @property string|null $mensaje
 */
class Mensajes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mensajes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mensaje'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mensaje' => 'Mensaje',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Mensajes;
use yii\data\ActiveDataProvider;
use app\models\Libros;
use app\models\Autores;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $numeroRegistros = Mensajes::find()->count();
        $aleatorio = random_int(0, $numeroRegistros - 1);
        $filaAleatoria = Mensajes::find()->offset($aleatorio)->one();;
        
        return $this->render('index',[
            'filaAleatoria' => $filaAleatoria,
        ]);
    }

    public function actionLibros()
    {
        $query = Libros::find()->select("id, isbn, titulo, fecha_publicacion");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('libros',[
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAutores()
    {
        $query = Autores::find()->select("id, nombre, apellidos");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('autores',[
            'dataProvider' => $dataProvider,
        ]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Libros', 'url' => ['/site/libros']],
            ['label' => 'Autores', 'url' => ['/site/autores']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Oscar Megía López 2020</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_autores.php
<?php
use app\widgets\Autores;
?>

<div>
    <?= Autores::widget([
        'id' => $model->id,
        'nombre' => $model->nombre,
        'apellidos' => $model->apellidos,
    ]) ?>
</div>

views/site/_libros.php
<?php
use app\widgets\Libros;
?>

<div>
    <?= Libros::widget([
        'id' => $model->id,
        'isbn' => $model->isbn,
        'titulo' => $model->titulo,
        'fecha_publicacion' => $model->fecha_publicacion,
    ]) ?>
</div>

views/site/autores.php
<?php

/* @var $this yii\web\View */
use yii\widgets\ListView;

$this->title = 'Práctica 1 Yii b';
?>
<div class="site-index">
    <div class="panel panel-default">
        <div class="panel-heading">Listado de Autores</div>
        <div class="panel-body">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr><th>ID</th><th>Nombre</th><th>Apellidos</th></tr>
                </thead>
                <tbody>
                    <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_autores',
                        'layout' => '{items}',
                    ]); ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\widgets\ListView;

$this->title = 'Práctica 1 Yii b';
?>
<div class="site-index">
    <div class="jumbotron">
        <h1 class="display-4"><?= $filaAleatoria->mensaje ?></h1>
    </div>
</div>

views/site/libros.php
<?php

/* @var $this yii\web\View */
use yii\widgets\ListView;

$this->title = 'Práctica 1 Yii b';
?>
<div class="site-index">
    <div class="panel panel-default">
        <div class="panel-heading">Listado de Libros</div>
        <div class="panel-body">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr><th>ID</th><th>ISBN</th><th>Titulo</th><th>Fecha publicación</th></tr>
                </thead>
                <tbody>
                    <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_libros',
                        'layout' => '{items}',
                    ]); ?>
                </tbody>
            </table>
        </div>
    </div>
</div>